//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.DashboardStarter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    internal sealed partial class Dashboard : global::System.Configuration.ApplicationSettingsBase {
        
        private static Dashboard defaultInstance = ((Dashboard)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Dashboard())));
        
        public static Dashboard Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string IconPath {
            get {
                return ((string)(this["IconPath"]));
            }
            set {
                this["IconPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowSidebar {
            get {
                return ((bool)(this["ShowSidebar"]));
            }
            set {
                this["ShowSidebar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Windows")]
        public string Localization {
            get {
                return ((string)(this["Localization"]));
            }
            set {
                this["Localization"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Teal")]
        public global::WPF.DashboardStarter.Enums.Skin CurrentSkin {
            get {
                return ((global::WPF.DashboardStarter.Enums.Skin)(this["CurrentSkin"]));
            }
            set {
                this["CurrentSkin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::WPF.DashboardStarter.Enums.IconColor IconColor {
            get {
                return ((global::WPF.DashboardStarter.Enums.IconColor)(this["IconColor"]));
            }
            set {
                this["IconColor"] = value;
            }
        }
    }
}
