//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.DashboardStarter.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF.DashboardStarter.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dashboard will restart.
        /// </summary>
        public static string App_RestartPending {
            get {
                return ResourceManager.GetString("App_RestartPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dashboard needs to restart.
        /// </summary>
        public static string App_RestartRequired {
            get {
                return ResourceManager.GetString("App_RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dashboard will shut down.
        /// </summary>
        public static string App_ShutdownPending {
            get {
                return ResourceManager.GetString("App_ShutdownPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dashboard needs to shut down.
        /// </summary>
        public static string App_ShutdownRequired {
            get {
                return ResourceManager.GetString("App_ShutdownRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your App Title Goes Here.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        public static string Disconnected_Connecting {
            get {
                return ResourceManager.GetString("Disconnected_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string HoverText_About {
            get {
                return ResourceManager.GetString("HoverText_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string HoverText_Close {
            get {
                return ResourceManager.GetString("HoverText_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand Sidebar.
        /// </summary>
        public static string HoverText_ExpandSidebar {
            get {
                return ResourceManager.GetString("HoverText_ExpandSidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch external Program.
        /// </summary>
        public static string HoverText_Launch {
            get {
                return ResourceManager.GetString("HoverText_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string HoverText_Logout {
            get {
                return ResourceManager.GetString("HoverText_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string HoverText_Maximize {
            get {
                return ResourceManager.GetString("HoverText_Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string HoverText_Messages {
            get {
                return ResourceManager.GetString("HoverText_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string HoverText_Minimize {
            get {
                return ResourceManager.GetString("HoverText_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize.
        /// </summary>
        public static string HoverText_Resize {
            get {
                return ResourceManager.GetString("HoverText_Resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retract Sidebar.
        /// </summary>
        public static string HoverText_RetractSidebar {
            get {
                return ResourceManager.GetString("HoverText_RetractSidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string HoverText_Settings {
            get {
                return ResourceManager.GetString("HoverText_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string LoginView_Button_Change {
            get {
                return ResourceManager.GetString("LoginView_Button_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string LoginView_Button_ChangePassword {
            get {
                return ResourceManager.GetString("LoginView_Button_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        public static string LoginView_Button_EnterPassword {
            get {
                return ResourceManager.GetString("LoginView_Button_EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginView_Button_Login {
            get {
                return ResourceManager.GetString("LoginView_Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again.
        /// </summary>
        public static string LoginView_Text_ErrorPleaseTryAgain {
            get {
                return ResourceManager.GetString("LoginView_Text_ErrorPleaseTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string LoginView_Text_NewPassword {
            get {
                return ResourceManager.GetString("LoginView_Text_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Passwords do not match. Please try again..
        /// </summary>
        public static string LoginView_Text_NewPasswordsNoMatch {
            get {
                return ResourceManager.GetString("LoginView_Text_NewPasswordsNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginView_Text_Password {
            get {
                return ResourceManager.GetString("LoginView_Text_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is expired. Please change your Password..
        /// </summary>
        public static string LoginView_Text_PasswordExpired {
            get {
                return ResourceManager.GetString("LoginView_Text_PasswordExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least {0} Characters long..
        /// </summary>
        public static string LoginView_Text_PasswordLength {
            get {
                return ResourceManager.GetString("LoginView_Text_PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain Numbers..
        /// </summary>
        public static string LoginView_Text_PasswordNumbers {
            get {
                return ResourceManager.GetString("LoginView_Text_PasswordNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Username do not match. Please try again..
        /// </summary>
        public static string LoginView_Text_PasswordRejected {
            get {
                return ResourceManager.GetString("LoginView_Text_PasswordRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain Special Characters..
        /// </summary>
        public static string LoginView_Text_PasswordSpecialCharacters {
            get {
                return ResourceManager.GetString("LoginView_Text_PasswordSpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain UppercaseCharacters..
        /// </summary>
        public static string LoginView_Text_PasswordUppercaseCharacters {
            get {
                return ResourceManager.GetString("LoginView_Text_PasswordUppercaseCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat new Password.
        /// </summary>
        public static string LoginView_Text_RepeatNewPassword {
            get {
                return ResourceManager.GetString("LoginView_Text_RepeatNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LoginView_Text_Username {
            get {
                return ResourceManager.GetString("LoginView_Text_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be at least {0} Characters long..
        /// </summary>
        public static string LoginView_Text_UsernameLength {
            get {
                return ResourceManager.GetString("LoginView_Text_UsernameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username does not exist. Please try again..
        /// </summary>
        public static string LoginView_Text_UsernameNotExist {
            get {
                return ResourceManager.GetString("LoginView_Text_UsernameNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter new Password.
        /// </summary>
        public static string LoginView_Title_ChangePassword {
            get {
                return ResourceManager.GetString("LoginView_Title_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Login Credentials.
        /// </summary>
        public static string LoginView_Title_Login {
            get {
                return ResourceManager.GetString("LoginView_Title_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Notification_DefaultButtonCancel {
            get {
                return ResourceManager.GetString("Notification_DefaultButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Notification_DefaultButtonConfirm {
            get {
                return ResourceManager.GetString("Notification_DefaultButtonConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string Notification_DefaultButtonDecline {
            get {
                return ResourceManager.GetString("Notification_DefaultButtonDecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Notification_DefaultCancel {
            get {
                return ResourceManager.GetString("Notification_DefaultCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Notification_DefaultConfirm {
            get {
                return ResourceManager.GetString("Notification_DefaultConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string Notification_DefaultDecline {
            get {
                return ResourceManager.GetString("Notification_DefaultDecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Notification_Error {
            get {
                return ResourceManager.GetString("Notification_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show this, if an Error occurs with the Application. Click &apos;{0}&apos; for the next Notification!.
        /// </summary>
        public static string Notification_ErrorDemoLongText {
            get {
                return ResourceManager.GetString("Notification_ErrorDemoLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error.
        /// </summary>
        public static string Notification_Fatal {
            get {
                return ResourceManager.GetString("Notification_Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show this, if a Fatal Error occurs with the Application. Click &apos;{0}&apos; for the next Notification!.
        /// </summary>
        public static string Notification_FatalDemoLongText {
            get {
                return ResourceManager.GetString("Notification_FatalDemoLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Notification_Info {
            get {
                return ResourceManager.GetString("Notification_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a general Information for the User. Click &apos;{0}&apos; for the next Notification!.
        /// </summary>
        public static string Notification_InfoDemoLongText {
            get {
                return ResourceManager.GetString("Notification_InfoDemoLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Notification_Success {
            get {
                return ResourceManager.GetString("Notification_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the User that his Action has succeeded. Click &apos;{0}&apos; for the next Notification!.
        /// </summary>
        public static string Notification_SuccessDemoLongText {
            get {
                return ResourceManager.GetString("Notification_SuccessDemoLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Notification_Warn {
            get {
                return ResourceManager.GetString("Notification_Warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a Warning to the User. Click &apos;{0}&apos; for the next Notification!.
        /// </summary>
        public static string Notification_WarnDemoLongText {
            get {
                return ResourceManager.GetString("Notification_WarnDemoLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Notification_Welcome {
            get {
                return ResourceManager.GetString("Notification_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the WpfDashboardStarter! Click &apos;{0}&apos; for the next Notification!.
        /// </summary>
        public static string Notification_WelcomeDemoLongText {
            get {
                return ResourceManager.GetString("Notification_WelcomeDemoLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Setting_ChangeDoesNotRequireRestartAccept {
            get {
                return ResourceManager.GetString("Setting_ChangeDoesNotRequireRestartAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Backend needs to restart for the Changes to take Effect.
        /// </summary>
        public static string Setting_ChangeRequiresBackendRestart {
            get {
                return ResourceManager.GetString("Setting_ChangeRequiresBackendRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dashboard needs to restart for the Changes to take Effect.
        /// </summary>
        public static string Setting_ChangeRequiresDashboardRestart {
            get {
                return ResourceManager.GetString("Setting_ChangeRequiresDashboardRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart now.
        /// </summary>
        public static string Setting_ChangeRequiresRestartAccept {
            get {
                return ResourceManager.GetString("Setting_ChangeRequiresRestartAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart later.
        /// </summary>
        public static string Setting_ChangeRequiresRestartDecline {
            get {
                return ResourceManager.GetString("Setting_ChangeRequiresRestartDecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting &quot;{0}&quot; was successfully changed.
        /// </summary>
        public static string Setting_ChangeSuccessful {
            get {
                return ResourceManager.GetString("Setting_ChangeSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &quot;Windows&quot; to use the default Windows Language (if available).
        /// </summary>
        public static string Setting_LocalizationHover {
            get {
                return ResourceManager.GetString("Setting_LocalizationHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Language.
        /// </summary>
        public static string Setting_LocalizationLong {
            get {
                return ResourceManager.GetString("Setting_LocalizationLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Setting_LocalizationShort {
            get {
                return ResourceManager.GetString("Setting_LocalizationShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expands the Sidebar automatically when logged in.
        /// </summary>
        public static string Setting_ShowSidebarHover {
            get {
                return ResourceManager.GetString("Setting_ShowSidebarHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the Sidebar by default.
        /// </summary>
        public static string Setting_ShowSidebarLong {
            get {
                return ResourceManager.GetString("Setting_ShowSidebarLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Sidebar.
        /// </summary>
        public static string Setting_ShowSidebarShort {
            get {
                return ResourceManager.GetString("Setting_ShowSidebarShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dashboard needs to restart for the Changes to take Effect..
        /// </summary>
        public static string Setting_SkinsHover {
            get {
                return ResourceManager.GetString("Setting_SkinsHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the Color Scheme.
        /// </summary>
        public static string Setting_SkinsLong {
            get {
                return ResourceManager.GetString("Setting_SkinsLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Scheme.
        /// </summary>
        public static string Setting_SkinsShort {
            get {
                return ResourceManager.GetString("Setting_SkinsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Programs.
        /// </summary>
        public static string SidebarLaunch_Title {
            get {
                return ResourceManager.GetString("SidebarLaunch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string SidebarMessages_Title {
            get {
                return ResourceManager.GetString("SidebarMessages_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SidebarSettings_Title {
            get {
                return ResourceManager.GetString("SidebarSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Status.
        /// </summary>
        public static string SidebarStatus_Title {
            get {
                return ResourceManager.GetString("SidebarStatus_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests.
        /// </summary>
        public static string SidebarTest_Title {
            get {
                return ResourceManager.GetString("SidebarTest_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in User.
        /// </summary>
        public static string Titlebar_LoggedInUser {
            get {
                return ResourceManager.GetString("Titlebar_LoggedInUser", resourceCulture);
            }
        }
    }
}
